theme: jekyll-theme-cayman
title: [Adversarial Black-Box Attacks on Automatic Speech Recognition Systems using Multi-Objective Evolutionary Optimization]
description: ["Authors: Shreya Khare, Rahul Aralikatte, Senthil Mani"]